server:
  port: ${NOTIFICATION_PORT:8080}
spring:
  application:
    name: notification-api
  mail:
    host: smtp.gmail.com
    port: 587
    username: "mcar7service@gmail.com"
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: movies-group # ?????????? ??? ?????? ????????????
      auto-offset-reset: earliest # ? ?????? ??????? ?????? ???? (earliest/latest)
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*" # ????????? ?????????????? ????? DTO-???????
  threads:
    virtual:
      enabled: true
tor:
  email:
    target: ${TARGET_EMAIL}
grpc:
  server:
    start: false
