server:
  port: 8080
spring:
  application:
    name: waittor
  r2dbc:
    url: r2dbc:postgresql://${PG_HOST}:${PG_PORT}/tor_db?sslMode=DISABLE
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  mail:
    host: smtp.gmail.com
    port: 587
    username: "mcar7service@gmail.com"
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
tor:
  url:
    login: "https://rutracker.org/forum/login.php"
    search: "https://rutracker.org/forum/tracker.php?f=%s&nm=%s"
  authenticate:
    login: ${TOR_LOGIN}
    password: ${TOR_PASS}
  email:
    target: ${TARGET_EMAIL}
