server:
  port: ${DATA_PORT:8080}
spring:
  application:
    name: data-api
  r2dbc:
    url: r2dbc:postgresql://${PG_HOST}:${PG_PORT}/tor_db?sslMode=DISABLE
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092} # ????? ????? Kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
tor:
  url:
    login: "https://rutracker.org/forum/login.php"
    search: "https://rutracker.org/forum/tracker.php?f=%s&nm=%s"
  authenticate:
    login: ${TOR_LOGIN}
    password: ${TOR_PASS}
#grpc:
#  client:
#    movie-service: # имя канала, используется в коде
#      address: 'static://localhost:19090'
#      negotiation-type: plaintext # отключает TLS для локальной разработки
