server:
  port: 8080
spring:
  application:
    name: ai-api
  main:
    web-application-type: none
  ai:
    ollama:
      base-url: http://${OLLAMA_QWEN_HOST}:11434
      chat:
        model: qwen2.5-coder:1.5b
grpc:
  port: 19090
  server:
    start: false
